import { DMMF } from '@prisma/generator-helper';
import { generateTables } from './table';
import { generateProject, ProjectOptions } from './project';

export const autoGeneratedComment = `//// ------------------------------------------------------
//// THIS FILE WAS AUTOMATICALLY GENERATED (DO NOT MODIFY)
//// ------------------------------------------------------`;

export function generateDBMLSchema(
  dmmf: DMMF.Document,
  allowManyToMany: boolean = true,
  mapToDbSchema: boolean = false,
  projectOptions?: ProjectOptions
): string {
  const tables = generateTables(dmmf.datamodel.models, mapToDbSchema);

  for (let model of dmmf.datamodel.models) {
    console.log("%%%%%%%%%%%%%%",model);
  }

  const project = projectOptions ? generateProject(projectOptions) : [];

  return [
    autoGeneratedComment,
    ...project,
    ...tables
  ].join('\n\n');
}
